export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const CHANGE_TAB = 'CHANGE_TAB';

export const GET_PROVIDER = 'GET_PROVIDER';
export const GET_PROVIDER_SUCCESS = 'GET_PROVIDER_SUCCESS';
export const GET_PROVIDER_FAILED = 'GET_PROVIDER_FAILED';

export const CLOSE_PROFILE_COMPLETE_MODAL = 'CLOSE_PROFILE_COMPLETE_MODAL';

export const UPDATE_PROFILE_COMPLETE_STATUS = 'UPDATE_PROFILE_COMPLETE_STATUS';

export const UPDATE_PROVIDER_TWITTER = 'UPDATE_PROVIDER_TWITTER';
export const UPDATE_PROVIDER_TWITTER_SUCCESS = 'UPDATE_PROVIDER_TWITTER_SUCCESS';
export const UPDATE_PROVIDER_TWITTER_FAILURE = 'UPDATE_PROVIDER_TWITTER_FAILURE';

export const UPDATE_PROVIDER_FACEBOOK = 'UPDATE_PROVIDER_FACEBOOK';
export const UPDATE_PROVIDER_FACEBOOK_SUCCESS = 'UPDATE_PROVIDER_FACEBOOK_SUCCESS';
export const UPDATE_PROVIDER_FACEBOOK_FAILURE = 'UPDATE_PROVIDER_FACEBOOK_FAILURE';

export const UPDATE_PROVIDER_INSTAGRAM = 'UPDATE_PROVIDER_INSTAGRAM';
export const UPDATE_PROVIDER_INSTAGRAM_SUCCESS = 'UPDATE_PROVIDER_INSTAGRAM_SUCCESS';
export const UPDATE_PROVIDER_INSTAGRAM_FAILURE = 'UPDATE_PROVIDER_INSTAGRAM_FAILURE';

export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAILED = 'GET_APPOINTMENT_FAILED';

export const CHECK_IN_APPOINTMENT = 'CHECK_IN_APPOINTMENT';
export const CHECK_IN_APPOINTMENT_SUCCESS = 'CHECK_IN_APPOINTMENT_SUCCESS';
export const CHECK_IN_APPOINTMENT_FAILED = 'CHECK_IN_APPOINTMENT_FAILED';

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAILED = 'GET_APPOINTMENTS_FAILED';

export const GET_APPOINTMENTS_PENDING = 'GET_APPOINTMENTS_PENDING';
export const GET_APPOINTMENTS_PENDING_SUCCESS =
  'GET_APPOINTMENTS_PENDING_SUCCESS';
export const GET_APPOINTMENTS_PENDING_FAILED =
  'GET_APPOINTMENTS_PENDING_FAILED';

export const CONFIRM_REQUEST_NEW_CLIENT = 'CONFIRM_REQUEST_NEW_CLIENT';
export const CONFIRM_REQUEST_NEW_CLIENT_SUCCESS =
  'CONFIRM_REQUEST_NEW_CLIENT_SUCCESS';
export const CONFIRM_REQUEST_NEW_CLIENT_FAILED =
  'CONFIRM_REQUEST_NEW_CLIENT_FAILED';

export const CONFIRM_REQUEST_EXIST_CLIENT = 'CONFIRM_REQUEST_EXIST_CLIENT';
export const CONFIRM_REQUEST_EXIST_CLIENT_SUCCESS =
  'CONFIRM_REQUEST_EXIST_CLIENT_SUCCESS';
export const CONFIRM_REQUEST_EXIST_CLIENT_FAILED =
  'CONFIRM_REQUEST_EXIST_CLIENT_FAILED';

export const CONFIRM_CONNECTED_CLIENT = 'CONFIRM_CONNECTED_CLIENT';
export const CONFIRM_CONNECTED_CLIENT_SUCCESS =
  'CONFIRM_CONNECTED_CLIENT_SUCCESS';
export const CONFIRM_CONNECTED_CLIENT_FAILED =
  'CONFIRM_CONNECTED_CLIENT_FAILED';

export const GET_APPOINTMENT_SLOTS = 'GET_APPOINTMENT_SLOTS';
export const GET_APPOINTMENT_SLOTS_SUCCESS = 'GET_APPOINTMENT_SLOTS_SUCCESS';
export const GET_APPOINTMENT_SLOTS_FAILED = 'GET_APPOINTMENT_SLOTS_FAILED';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILED = 'CREATE_APPOINTMENT_FAILED';

export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_REQUEST_SUCCESS =
  'CREATE_APPOINTMENT_REQUEST_SUCCESS';
export const CREATE_APPOINTMENT_REQUEST_FAILED =
  'CREATE_APPOINTMENT_REQUEST_FAILED';

export const UPDATE_APPOINTMENT_BY_ID = 'UPDATE_APPOINTMENT_BY_ID';
export const UPDATE_APPOINTMENT_BY_ID_SUCCESS =
  'UPDATE_APPOINTMENT_BY_ID_SUCCESS';
export const UPDATE_APPOINTMENT_BY_ID_FAILED =
  'UPDATE_APPOINTMENT_BY_ID_FAILED';

export const DELETE_APPOINTMENT_BY_ID = 'DELETE_APPOINTMENT_BY_ID';
export const DELETE_APPOINTMENT_BY_ID_SUCCESS =
  'DELETE_APPOINTMENT_BY_ID_SUCCESS';
export const DELETE_APPOINTMENT_BY_ID_FAILED =
  'DELETE_APPOINTMENT_BY_ID_FAILED';

export const GET_PRODUCTS_APPOINTMENT = 'GET_PRODUCTS_APPOINTMENT';
export const GET_PRODUCTS_APPOINTMENT_SUCCESS =
  'GET_PRODUCTS_APPOINTMENT_SUCCESS';
export const GET_PRODUCTS_APPOINTMENT_FAILED =
  'GET_PRODUCTS_APPOINTMENT_FAILED';

export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';
export const GET_PRODUCTS_BY_ID_SUCCESS = 'GET_PRODUCTS_BY_ID_SUCCESS';
export const GET_PRODUCTS_BY_ID_FAILED = 'GET_PRODUCTS_BY_ID_FAILED';

export const GET_SUB_CLIENTS = 'GET_SUB_CLIENTS';
export const GET_SUB_CLIENTS_SUCCESS = 'GET_SUB_CLIENTS_SUCCESS';
export const GET_SUB_CLIENTS_FAILED = 'GET_SUB_CLIENTS_FAILED';

export const RESET_SUB_CLIENTS = 'RESET_SUB_CLIENTS';

export const GET_SUB_CLIENTS_SEARCH = 'GET_SUB_CLIENTS_SEARCH';
export const GET_SUB_CLIENTS_SEARCH_SUCCESS = 'GET_SUB_CLIENTS_SEARCH_SUCCESS';
export const GET_SUB_CLIENTS_SEARCH_FAILED = 'GET_SUB_CLIENTS_SEARCH_FAILED';

export const GET_SUB_CLIENTS_REVIEW = 'GET_SUB_CLIENTS_REVIEW';
export const GET_SUB_CLIENTS_REVIEW_SUCCESS = 'GET_SUB_CLIENTS_REVIEW_SUCCESS';
export const GET_SUB_CLIENTS_REVIEW_FAILED = 'GET_SUB_CLIENTS_REVIEW_FAILED';

export const GET_CONNECTED_CLIENTS = 'GET_CONNECTED_CLIENTS';
export const GET_CONNECTED_CLIENTS_SUCCESS = 'GET_CONNECTED_CLIENTS_SUCCESS';
export const GET_CONNECTED_CLIENTS_FAILED = 'GET_CONNECTED_CLIENTS_FAILED';

export const GET_NOT_CONNECTED_CLIENTS = 'GET_NOT_CONNECTED_CLIENTS';
export const GET_NOT_CONNECTED_CLIENTS_SUCCESS =
  'GET_NOT_CONNECTED_CLIENTS_SUCCESS';
export const GET_NOT_CONNECTED_CLIENTS_FAILED =
  'GET_NOT_CONNECTED_CLIENTS_FAILED';

export const GET_SUB_CLIENT_BY_ID = 'GET_SUB_CLIENT_BY_ID';
export const GET_SUB_CLIENT_BY_ID_SUCCESS = 'GET_SUB_CLIENT_BY_ID_SUCCESS';
export const GET_SUB_CLIENT_BY_ID_FAILED = 'GET_SUB_CLIENT_BY_ID_FAILED';

export const GET_SUB_CLIENT_APPOINTMENTS_BY_ID =
  'GET_SUB_CLIENT_APPOINTMENTS_BY_ID';
export const GET_SUB_CLIENT_APPOINTMENTS_BY_ID_SUCCESS =
  'GET_SUB_CLIENT_APPOINTMENTS_BY_ID_SUCCESS';
export const GET_SUB_CLIENT_APPOINTMENTS_BY_ID_FAILED =
  'GET_SUB_CLIENT_APPOINTMENTS_BY_ID_FAILED';

export const CREATE_SUB_CLIENTS = 'CREATE_SUB_CLIENTS';
export const CREATE_SUB_CLIENTS_SUCCESS = 'CREATE_SUB_CLIENTS_SUCCESS';
export const CREATE_SUB_CLIENTS_FAILED = 'CREATE_SUB_CLIENTS_FAILED';

export const UPDATE_SUB_CLIENT = 'UPDATE_SUB_CLIENT';
export const UPDATE_SUB_CLIENT_SUCCESS = 'UPDATE_SUB_CLIENT_SUCCESS';
export const UPDATE_SUB_CLIENT_FAILED = 'UPDATE_SUB_CLIENT_FAILED';

export const DELETE_SUB_CLIENT_BY_ID = 'DELETE_SUB_CLIENT_BY_ID';
export const DELETE_SUB_CLIENT_BY_ID_SUCCESS =
  'DELETE_SUB_CLIENT_BY_ID_SUCCESS';
export const DELETE_SUB_CLIENT_BY_ID_FAILED = 'DELETE_SUB_CLIENT_BY_ID_FAILED';

export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const GET_CLIENT_FAILED = 'GET_CLIENT_FAILED';

export const MORE_DETAILS = 'MORE_DETAILS';
export const UPDATE_MORE_DETAILS = 'UPDATE_MORE_DETAILS';

export const UPDATE_PROVIDER = 'UPDATE_PROVIDER';
export const UPDATE_PROVIDER_SUCCESS = 'UPDATE_PROVIDER_SUCCESS';
export const UPDATE_PROVIDER_FAILED = 'UPDATE_PROVIDER_FAILED';

export const UPDATE_PROVIDER_DETAILS = 'UPDATE_PROVIDER_DETAILS';
export const UPDATE_PROVIDER_DETAILS_SUCCESS = 'UPDATE_PROVIDER_DETAILS_SUCCESS';
export const UPDATE_PROVIDER_DETAILS_FAILED = 'UPDATE_PROVIDER_DETAILS_FAILED';

export const UPDATE_PROVIDER_PROFILE_STATUS = 'UPDATE_PROVIDER_PROFILE_STATUS';
export const UPDATE_PROVIDER_PROFILE_STATUS_SUCCESS = 'UPDATE_PROVIDER_PROFILE_STATUS_SUCCESS';
export const UPDATE_PROVIDER_PROFILE_STATUS_FAILED = 'UPDATE_PROVIDER_PROFILE_STATUS_FAILED';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILED = 'UPDATE_CLIENT_FAILED';

export const UPDATE_PROVIDER_PASSWORD = 'UPDATE_PROVIDER_PASSWORD';
export const UPDATE_PROVIDER_PASSWORD_SUCCESS =
  'UPDATE_PROVIDER_PASSWORD_SUCCESS';
export const UPDATE_PROVIDER_PASSWORD_FAILED =
  'UPDATE_PROVIDER_PASSWORD_FAILED';

export const UPDATE_CLIENT_PASSWORD = 'UPDATE_CLIENT_PASSWORD';
export const UPDATE_CLIENT_PASSWORD_SUCCESS = 'UPDATE_CLIENT_PASSWORD_SUCCESS';
export const UPDATE_CLIENT_PASSWORD_FAILED = 'UPDATE_CLIENT_PASSWORD_FAILED';

export const UPDATE_CLIENT_ADDRESS = 'UPDATE_CLIENT_ADDRESS';
export const UPDATE_CLIENT_ADDRESS_SUCCESS = 'UPDATE_CLIENT_ADDRESS_SUCCESS';
export const UPDATE_CLIENT_ADDRESS_FAILED = 'UPDATE_CLIENT_ADDRESS_FAILED';

export const LOG_OUT = 'LOG_OUT';

export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_IN_GOOGLE_SUCCESS = 'SIGN_IN_GOOGLE_SUCCESS';
export const SIGN_IN_GOOGLE_FAILED = 'SIGN_IN_GOOGLE_FAILED';

export const SIGN_IN_FACEBOOK = 'SIGN_IN_FACEBOOK';
export const SIGN_IN_FACEBOOK_SUCCESS = 'SIGN_IN_FACEBOOK_SUCCESS';
export const SIGN_IN_FACEBOOK_FAILED = 'SIGN_IN_FACEBOOK_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_UP_PROVIDER = 'SIGN_UP_PROVIDER';
export const SIGN_UP_PROVIDER_SUCCESS = 'SIGN_UP_PROVIDER_SUCCESS';
export const SIGN_UP_PROVIDER_FAILED = 'SIGN_UP_PROVIDER_FAILED';

export const SIGN_UP_PROVIDER_GOOGLE = 'SIGN_UP_PROVIDER_GOOGLE';
export const SIGN_UP_PROVIDER_GOOGLE_SUCCESS =
  'SIGN_UP_PROVIDER_GOOGLE_SUCCESS';
export const SIGN_UP_PROVIDER_GOOGLE_FAILED = 'SIGN_UP_PROVIDER_GOOGLE_FAILED';

export const SIGN_UP_PROVIDER_FACEBOOK = 'SIGN_UP_PROVIDER_FACEBOOK';
export const SIGN_UP_PROVIDER_FACEBOOK_SUCCESS =
  'SIGN_UP_PROVIDER_FACEBOOK_SUCCESS';
export const SIGN_UP_PROVIDER_FACEBOOK_FAILED =
  'SIGN_UP_PROVIDER_FACEBOOK_FAILED';

export const SIGN_UP_CLIENT = 'SIGN_UP_CLIENT';
export const SIGN_UP_CLIENT_SUCCESS = 'SIGN_UP_CLIENT_SUCCESS';
export const SIGN_UP_CLIENT_FAILED = 'SIGN_UP_CLIENT_FAILED';

export const SIGN_UP_CLIENT_GOOGLE = 'SIGN_UP_CLIENT_GOOGLE';
export const SIGN_UP_CLIENT_GOOGLE_SUCCESS = 'SIGN_UP_CLIENT_GOOGLE_SUCCESS';
export const SIGN_UP_CLIENT_GOOGLE_FAILED = 'SIGN_UP_CLIENT_GOOGLE_FAILED';

export const SIGN_UP_CLIENT_FACEBOOK = 'SIGN_UP_CLIENT_FACEBOOK';
export const SIGN_UP_CLIENT_FACEBOOK_SUCCESS =
  'SIGN_UP_CLIENT_FACEBOOK_SUCCESS';
export const SIGN_UP_CLIENT_FACEBOOK_FAILED = 'SIGN_UP_CLIENT_FACEBOOK_FAILED';

export const SIGN_UP_CLIENT_APPLE = 'SIGN_UP_CLIENT_APPLE';
export const SIGN_UP_CLIENT_APPLE_SUCCESS =
  'SIGN_UP_CLIENT_APPLE_SUCCESS';
export const SIGN_UP_CLIENT_APPLE_FAILED = 'SIGN_UP_CLIENT_APPLE_FAILED';

export const VERIFICATION_EMAIL = 'VERIFICATION_EMAIL';
export const VERIFICATION_EMAIL_SUCCESS = 'VERIFICATION_EMAIL_SUCCESS';
export const VERIFICATION_EMAIL_FAILED = 'VERIFICATION_EMAIL_FAILED';

export const VERIFICATION_SECURE_CODE = 'VERIFICATION_SECURE_CODE';
export const VERIFICATION_SECURE_CODE_CLIENT =
  'VERIFICATION_SECURE_CODE_CLIENT';

export const VERIFICATION_EMAIL_CLIENT = 'VERIFICATION_EMAIL_CLIENT';
export const VERIFICATION_EMAIL_CLIENT_SUCCESS =
  'VERIFICATION_EMAIL_CLIENT_SUCCESS';
export const VERIFICATION_EMAIL_CLIENT_FAILED =
  'VERIFICATION_EMAIL_CLIENT_FAILED';

export const CHANGE_STEP_PROVIDER = 'CHANGE_STEP_PROVIDER';
export const CHANGE_STEP_CLIENT = 'CHANGE_STEP_CLIENT';

export const CHANGE_STEP_FORGOT_PASSWORD = 'CHANGE_STEP_FORGOT_PASSWORD';
export const FORGOT_PASSWORD_EMAIL = 'FORGOT_PASSWORD_EMAIL';
export const FORGOT_VERIFY_SECURE_CODE = 'FORGOT_VERIFY_SECURE_CODE';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const GET_APPOINTMENTS_REVIEW = 'GET_APPOINTMENTS_REVIEW';
export const GET_APPOINTMENTS_REVIEW_SUCCESS =
  'GET_APPOINTMENTS_REVIEW_SUCCESS';
export const GET_APPOINTMENTS_REVIEW_FAILED = 'GET_APPOINTMENTS_REVIEW_FAILED';
