import { t, translations } from 'locales';

export const LABELS = {
  email: t(translations.form.email),
  backTitle: t(translations.createPayment.backTitle),
  newClient: t(translations.createPayment.newClient),
  selectAClient: t(translations.createPayment.selectAClient),
  firstName: t(translations.createPayment.firstName),
  lastName: t(translations.createPayment.lastName),
  telephone: t(translations.createPayment.telephone),
  preview: t(translations.createPayment.preview),
  paymentMethod: t(translations.createPayment.paymentMethod),
  invoiceBalance: t(translations.createPayment.invoiceBalance),
  receiptTotal: t(translations.createPayment.receiptTotal),
  receiptDate: t(translations.createPayment.receiptDate),
  invoiceDetails: t(translations.createPayment.invoiceDetails),
  estimateDetails: t(translations.createPayment.estimatesDetails),
  invoice: t(translations.createPayment.invoice),
  estimate: t(translations.createPayment.estimate),
  selectInvoice: t(translations.createPayment.selectInvoice),
  selectEstimate: t(translations.createPayment.selectEstimate),
  reason: t(translations.createPayment.reason),
  notes: t(translations.createPayment.notes),
  sendReceipt: t(translations.createPayment.sendReceipt),
  save: t(translations.createPayment.save),
  notValidFirstName: t(translations.createPayment.notValidFirstName),
  notValidLastName: t(translations.createPayment.notValidLastName),
  selectClient: t(translations.createPayment.selectClient),
  selectMethod: t(translations.createPayment.selectMethod),
  selectInvoiceNote: t(translations.createPayment.selectInvoiceNote),
  selectEstimateNote: t(translations.createPayment.selectEstimateNote),
  selectEmail: t(translations.createPayment.selectEmail),
  noName: t(translations.createPayment.noName),
  putTotal: t(translations.createPayment.putTotal),
  selectDate: t(translations.createPayment.selectDate),
};
