import { Dimensions, StyleSheet } from 'react-native';
import COLORS from 'utils/colors';
import FONTS from 'utils/fonts';
import { margin, shadow } from 'utils/styles';

export const chatStyles = StyleSheet.create({
  messagesContainer: {
    backgroundColor: COLORS.whiteFour,
  },
  send: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 32,
    height: 32,
  },
  input: {
    justifyContent: 'center',
    ...margin(0, 0),
    paddingTop: 10,
    fontFamily: FONTS.medium,
    color: COLORS.blackLacquer,
  },
  toolbar: {
    alignItems: 'center',
    minHeight: 44,
    padding: 10,
    backgroundColor: COLORS.whiteFour,
    borderWidth: 1,
    borderColor: COLORS.whiteGray,
    borderRadius: 22,
  },
  toolbarContainer: {
    padding: 20,
    backgroundColor: COLORS.white,
    borderTopWidth: 0,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: -6,
    },
    shadowOpacity: 0.025,
    shadowRadius: 4,
    elevation: 5,
  },
  bubble: {
    marginRight: 16,
    marginLeft: 92,
    padding: 16,
    backgroundColor: COLORS.clearBlue,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    ...shadow(),
  },
  participantBubble: {
    marginRight: 92,
    marginLeft: -32, // To overlap transparent avatar
    padding: 16,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    ...shadow(),
  },
  scrollToBottomButton: {
    right: 30,
    height: 50,
    width: 50,
    backgroundColor: COLORS.white,
    borderRadius: 25,
    borderWidth: 0,
    ...shadow(),
  },
  unreadBar: {
    position: 'absolute',
    right: 0,
    top: 0,
    alignItems: 'center',
    width: Dimensions.get('screen').width + 8,
    marginRight: -8,
    padding: 2,
    backgroundColor: COLORS.clearBlue20,
  },
  imageBack: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginLeft: 24,
  },
  imageConnected: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    marginLeft: 8,
  },
  closeImage: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  titleLeftStyle: {
    fontSize: 18,
    marginLeft: 8,
    fontFamily: FONTS.bold,
  },
  title: {
    paddingHorizontal: 24,
    paddingTop: 24,
    fontSize: 14,
    fontFamily: FONTS.book,
    color: COLORS.brownishGrey,
  },
  appointmentContainer: {
    borderRadius: 7,
    marginHorizontal: 24,
    marginTop: 24,
    backgroundColor: COLORS.white,
    padding: 12,
  },
  shadow: {
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 5,
  },
  avatar: {
    marginRight: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    resizeMode: 'cover',
  },
  appointmentTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontFamily: FONTS.medium,
  },
  appointmentDateTitle: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.brownishGrey,
    fontFamily: FONTS.book,
  },
  appointmentDateValue: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.black,
    fontFamily: FONTS.medium,
  },
  appointmentServiceTitle: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.brownishGrey,
    fontFamily: FONTS.book,
  },
  anotherTimeSlots: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.red,
    fontFamily: FONTS.book,
  },
  appointmentServiceValue: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.black,
    fontFamily: FONTS.medium,
  },
  separator: {
    borderBottomWidth: 1,
    borderColor: COLORS.whiteGray,
    marginVertical: 12,
  },
  styleButton: {
    paddingVertical: 10,
    width: '40%',
  },
  styleCancel: {
    borderWidth: 2,
    borderColor: COLORS.orange,
    backgroundColor: COLORS.white,
  },
  textCancel: {
    fontSize: 14,
    color: COLORS.black,
  },
  styleConfirm: {
    marginLeft: 12,
    borderWidth: 2,
    borderColor: COLORS.orange,
    backgroundColor: COLORS.orange,
  },
  textConfirm: {
    fontSize: 14,
  },
  endPosition: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  chooseModalView: {
    flex: 1,
    // backgroundColor: COLORS.backgroundModal,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chooseView: {
    width: '90%',
    paddingHorizontal: 32,
    paddingVertical: 24,
    backgroundColor: COLORS.white,
    borderRadius: 20,
  },
  centeredView: {
    flex: 1,
    backgroundColor: COLORS.backgroundModal,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  modalView: {
    width: '100%',
    height: '80%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: COLORS.white,
    borderRadius: 5,
  },
  titleChooseModal: {
    fontSize: 16,
    fontFamily: FONTS.medium,
    textAlign: 'center',
  },
  createNew: {
    marginTop: 16,
    borderRadius: 5,
    backgroundColor: COLORS.red,
  },
  connectClient: {
    marginTop: 16,
    borderRadius: 5,
    backgroundColor: COLORS.forestgreen,
  },
});
