import { translations } from "locales";

export const BENIFIT_CHART = [
  {
    title: translations.subscription.accessToAppAndWeb,
    standard: true,
    premium: true,
    lite: true,
    bg: true,
  },
  {
    title: translations.subscription.accessForYou,
    standard: true,
    premium: true,
    lite: true,
    bg: false,
  },
  {
    title: translations.subscription.messageClients,
    standard: true,
    premium: true,
    lite: true,
    bg: true,
  },
  {
    title: translations.subscription.menageAppointments,
    standard: true,
    premium: true,
    lite: true,
    bg: false,
  },
  {
    title: translations.subscription.clientsBook,
    standard: true,
    premium: true,
    lite: true,
    bg: true,
  },
  {
    title: translations.subscription.manageClients,
    standard: true,
    premium: true,
    lite: true,
    bg: false,
  },
  {
    title: translations.subscription.trackExpenses,
    standard: true,
    premium: true,
    lite: true,
    bg: true,
  },
  {
    title: translations.subscription.trackSales,
    standard: true,
    premium: true,
    lite: false,
    bg: false,
  },
  {
    title: translations.subscription.createInvoice,
    standard: true,
    premium: true,
    lite: false,
    bg: true,
  },
  {
    title: translations.subscription.salesAdvertising,
    standard: false,
    premium: '5',
    lite: false,
    bg: false,
  },
  {
    title: translations.subscription.loyaltyProgram,
    standard: false,
    premium: true,
    lite: false,
    bg: true,
  },
  {
    title: translations.subscription.socialMedia,
    standard: false,
    premium: true,
    lite: false,
    bg: false,
  },
  {
    title: translations.subscription.acceptPayments,
    standard: false,
    premium: true,
    lite: false,
    bg: true,
  },
]